Create get incidents info controller
Arquisoft/InciManager_i2b pull request #14
Opened 2018-03-11 17:58 UTC by UO251436

Fixes #4 
I struggled quite a lot testing the controller and just did what I though was better, so tests may be still lacking :/

2018-03-11 18:04 UTC, alejgh requested changes
I would prefer to avoid using MongoDB for now until it is completely necessary (its requires starting the mongo server, and it makes the dockerfile more complex). Could you change MongoDB for an in-memory database like h2? I'm sorry I forgot to mention this before :sweat_smile:

2018-03-11 18:06 UTC, alejgh commented
To use h2 you need to add the following dependency:
```
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <scope>runtime</scope>
</dependency>
```

You will also need to make the IncidentsRepository extend CrusRepository instead of MongoRepository, and remove the mongo configuration from the properties file.
I think that will be enough for it to work.

2018-03-11 18:07 UTC, UO251436 commented
OK, shouldn't take long, no problem 👍

2018-03-12 09:26 UTC, alejgh approved these changes

2018-03-12 09:26 UTC, merged