I think it is done, but i dont know how to do the withOperator part
Arquisoft/InciManager_i2b pull request #25
Opened 2018-03-17 23:54 UTC by tejido18

2018-03-18 11:13 UTC, alejgh requested changes

2018-03-18 11:13 UTC, alejgh commented on src/main/java/com/uniovi/services/TopicService.java
> +			aux.add("standard");
Here you can remove the `if(aux.size()==0)`. For now every incident will have the standard topic.

2018-03-18 11:13 UTC, alejgh commented on src/main/java/com/uniovi/services/TopicService.java
> +			aux.add("standard");
Regarding the "withOperator" topic, operators can be stored in the properties map of the incident, so you can do something like this:
```java
for (String key : incident.getProperties().keySet()) {
    if ("operators".equals(key)) {
        aux.add("withOperator");
        break;
    }
}
```

2018-03-18 11:13 UTC, alejgh commented on src/main/java/com/uniovi/services/TopicService.java
> +			aux.add("standard");
Also, it seems like you moved every test from 'src/test' to 'src/main/test', so please put the tests back to 'src/test' if you can.

2018-03-18 11:13 UTC, alejgh commented on src/main/java/com/uniovi/services/TopicService.java
> +			aux.add("standard");
And finally, codacy seems to be complaining about `if(!incident.getLocation().equals(null))`, so use `==` instead. 
The Travis build is also failing but 'm pretty sure this is not your fault, so I will make some tests to see why it is failing. For now you can work on the previous comments while I try to fix Travis.

2018-03-18 19:49 UTC, alejgh approved these changes

2018-03-20 00:15 UTC, tejido18 commented
Is it ok?

2018-03-20 13:08 UTC, alejgh approved these changes

2018-03-20 13:08 UTC, alejgh commented
It's ok, sorry for the wait.

2018-03-21 16:03 UTC, carmee-en commented
Codecov will be patched in future pull requests. Merging branch.

2018-03-21 16:03 UTC, merged